Figmagic rewrite to use .figmagic.json
andredovale/figmagic pull request #1
Opened 2020-02-03 18:59 UTC by andredovale

2020-02-11 02:59 UTC, thiagomre submitted a review, later dismissed

2020-02-11 17:40 UTC, mkny requested changes

2020-02-11 17:40 UTC, mkny commented on package.json
> +		"build": "rollup -c && chmod u+x dist/index.js",
Eu acho que seria melhor utilizar de scripts em node, pra efetuar essas operações.
No caso aí, o chmod e o rm -rf são comandos específicos de sistemas Unix.

2020-02-11 17:40 UTC, mkny commented on rollup.config.js
> +		// banner: `#!/bin/sh\n':' //# comment; exec /usr/bin/env node "$0" "$@"`,
Comentário necessário?

2020-02-11 17:40 UTC, mkny commented on src/functions/setup-token.ts
> +			throw new Error("styleKey don't founded");
```suggestion
			throw new Error("styleKey not found");
```

2020-02-11 17:40 UTC, mkny commented on src/functions/get-from-api.ts
> +				throw new Error("Error to get Figma metadata from API");
```suggestion
				throw new Error("Error getting Figma metadata from API");
```

2020-02-11 17:40 UTC, mkny commented on __tests__/functions/write-file.test.ts
> +	test("Without first parameter", () => {
Trocar nome aleatório por algo mais descritivo.
Ex: Should fail when file is not provided.

2020-02-11 17:40 UTC, mkny commented on __tests__/functions/write-file.test.ts
> +	test("Without second parameter", () => {
Should fail if `path` is not provided.

2020-02-13 13:28 UTC, mkny approved these changes

2020-02-14 13:31 UTC, thiagomre approved these changes
Changes ok

2020-02-14 13:34 UTC, merged