Output path for the tokens
andredovale/figmagic pull request #3
Opened 2020-02-05 15:29 UTC by andredovale

2020-02-11 03:09 UTC, thiagomre submitted a review, later dismissed

2020-02-14 17:44 UTC, thiagomre submitted a review, later dismissed
Change Ok

2020-02-20 21:25 UTC, mkny requested changes

2020-02-20 21:25 UTC, mkny commented on src/types/config.ts
> +	figmaJson: boolean; // export or not the original JSON from Figma API
Aqui que vão ficar esses comentários? Não seria melhor colocar num README.md ?

2020-02-20 21:25 UTC, mkny commented on src/types/config.ts
> +	outputFigmaJsonPath: string; // folder path for the original JSON from Figma API
Igual comentário anterior

2020-02-20 21:25 UTC, mkny commented on src/functions/parse-string.ts
> +
Esse espaço poderia ser removido.

2020-02-20 21:25 UTC, mkny commented on src/functions/process-token.ts
> +
Esse espaço poderia ser removido.

2020-02-20 21:25 UTC, mkny commented on src/functions/setup-token.ts
> +
Esse espaço poderia ser removido.

2020-02-20 21:25 UTC, mkny commented on package.json
> +	"version": "1.0.35",
Nesse arquivo, não tá no review, mas seria interessante colocar o jest como devDependencies ?

2020-02-27 14:17 UTC, albanomatheus requested changes

2020-02-27 14:17 UTC, albanomatheus commented on .figmagic.json
> +	"outputFigmaTokensPath": "tokens",
Não foi possível extrair os tokens com outro caminho definido nessa linha, apenas pelo comando `figmagic -o teste`

2020-02-27 14:25 UTC, andredovale commented on src/types/config.ts
> +	figmaJson: boolean; // export or not the original JSON from Figma API
Vou acatar a sugestão no PR #4 . 👍

2020-02-27 14:27 UTC, andredovale commented on src/types/config.ts
> +	outputFigmaJsonPath: string; // folder path for the original JSON from Figma API
Vou acatar a sugestão no PR #4 . 👍

2020-02-27 18:20 UTC, andredovale commented on .figmagic.json
> +	"outputFigmaTokensPath": "tokens",
Resolvido no 2ee0190 .

2020-02-27 18:21 UTC, andredovale commented on package.json
> +	"version": "1.0.35",
Resolvido no 2ee0190 .

2020-02-27 18:24 UTC, andredovale commented on src/functions/parse-string.ts
> +
Eu separo os `imports` visualmente em três blocos: dependências externas, do projeto mas fora do escopo local, e as locais.

2020-03-02 14:30 UTC, mkny requested changes

2020-03-02 14:30 UTC, mkny commented on package.json
>  		"setup": "rimraf yarn.lock node_modules/ /usr/local/lib/node_modules/figmagic && npm install -g",
Esse comando executa em /usr/local esse é um path apenas pra sistemas unix.

2020-03-02 16:48 UTC, merged