Documentation
andredovale/figmagic pull request #4
Opened 2020-02-07 18:52 UTC by andredovale

2020-02-14 14:38 UTC, albanomatheus requested changes

2020-02-14 14:38 UTC, albanomatheus commented on readme.md
> +This library is based in the original [Figmagic](https://github.com/mikaelvesavuori/figmagic) by [Mikael Vesavuori](https://github.com/mikaelvesavuori).
based on

2020-02-14 14:38 UTC, albanomatheus commented on readme.md
> +Extract design tokens for any value in Figma. A typical use case for the generated documents is to use the extracted values as a token base in CSS systems that support external values (such as Styled
```suggestion
Extract design tokens from any value in Figma. A typical use case for the generated documents is to use the extracted values as a token base in CSS systems that support external values (such as Styled Components, other CSS-in-JS libraries, or Sass).
```

2020-02-14 14:38 UTC, albanomatheus commented on readme.md
> +Figmagic have a default `.figmagic.json`, and, to work without modifications requires that your document structure is identical to the template available at [Figma example project].
```suggestion
Figmagic has a default `.figmagic.json`, and, to work without modifications requires that your document structure is identical to the template available at [Figma example project].
```

2020-02-14 14:38 UTC, albanomatheus commented on readme.md
> +- [ ] Implement the option to specifc the `key` to use as name for the token.
```suggestion
- [ ] Implement the option to specify the `key` to use as name for the token.
```

2020-02-14 14:38 UTC, albanomatheus commented on readme.md
> +If you need to secure your Figma input data, is possible to use a enviroment file named `.env` in the same level where you are using the cli command `figmagic`.
```suggestion
If you need to secure your Figma input data, is possible to use a environment file named `.env` in the same level where you are using the cli command `figmagic`.
```

2020-02-17 20:19 UTC, thiagofuzaro requested changes

2020-02-17 20:19 UTC, thiagofuzaro commented on src/types/config.ts
> +	apiBaseUrl: string; // Base URL from Figma API
```suggestion
	apiBaseUrl: string; // Figma API base URL
```

2020-02-17 20:19 UTC, thiagofuzaro commented on src/types/config.ts
> +	figmaUrl: string; // URL from the project you need to extract the tokens
```suggestion
	figmaUrl: string; // Figma's file URL param
```
Acho que até o nome do atributo poderia ser alterado. Tipo fileParam, ou fileId.

2020-02-17 20:19 UTC, thiagofuzaro commented on src/types/config.ts
> +	figmaToken: string; // Your user token from Figma to connect on Figma API
```suggestion
	figmaToken: string; // Your Figma's user token to connect with API
```

2020-02-17 20:19 UTC, thiagofuzaro commented on src/types/config.ts
> +	figmaPage: string; // Page from project to extract the tokens
Project page to extract tokens
```suggestion
	figmaPage: string; // Project page to extract tokens
```

2020-02-17 20:19 UTC, thiagofuzaro commented on src/types/config.ts
> +	outputColorFormat: "hexadecimal" | "hsl" | "hsla" | "rgb" | "rgba"; // TODO: Prefered format color to output the tokens (work with `token[#].processValue = "color";`)
```suggestion
	outputColorFormat: "hexadecimal" | "hsl" | "hsla" | "rgb" | "rgba"; // TODO: Prefered format color to output tokens (work with `token[#].processValue = "color";`)
```

2020-02-17 20:19 UTC, thiagofuzaro commented on src/types/config.ts
> +		| "vw"; // TODO: Prefered css unit to output the tokens
```suggestion
		| "vw"; // TODO: Prefered css unit to output tokens
```

2020-02-17 20:19 UTC, thiagofuzaro commented on src/types/config.ts
> +	outputFigmaJsonPath: string; // Folder path for the original JSON from Figma API
```suggestion
	outputFigmaJsonPath: string; // Folder's path of the original JSON file from Figma Api
```

2020-02-17 20:19 UTC, thiagofuzaro commented on src/types/config.ts
> +	outputFigmaJsonName: string; // File name for the original JSON from Figma API
```suggestion
	outputFigmaJsonName: string; // Name of the original JSON file from Figma API
```

2020-02-17 20:19 UTC, thiagofuzaro commented on src/types/config.ts
> +	outputFigmaTokensPath: string; // Folder path for the generated tokens
```suggestion
	outputFigmaTokensPath: string; // Generated tokens folder's path
```

2020-02-17 20:19 UTC, thiagofuzaro commented on src/types/config.ts
> +	outputNameFormat: "camel" | "kebab" | "lower" | "snake" | "start" | "upper"; // Prefered string case to output the tokens keys
```suggestion
	outputNameFormat: "camel" | "kebab" | "lower" | "snake" | "start" | "upper"; // String case Prefered to output tokens keys
```

2020-02-17 20:19 UTC, thiagofuzaro commented on src/types/config.ts
> +		frameName: string | string[]; // Frame identification name on Figma Page (needed as direct child from page)
```suggestion
		frameName: string | string[]; // Frame's name on Figma page (required as direct child from page)
```

2020-02-17 20:19 UTC, thiagofuzaro commented on src/types/config.ts
> +		name: string; // Name of the file to output this token
```suggestion
		name: string; // File name to output this token
```

2020-02-17 20:19 UTC, thiagofuzaro commented on src/types/config.ts
> +		path: string; // Path of the value for this token, in the same format from `lodash.get`
```suggestion
		path: string; // Value's path of this token. "lodash.get" same format
```

2020-02-17 20:19 UTC, thiagofuzaro commented on src/types/config.ts
> +		fallback?: string; // Used for cases when the path don't exist, but need to return a value to token
```suggestion
		fallback?: string; // Used when the path doesn't exists, but need to return a value to this token
```

2020-02-17 20:19 UTC, thiagofuzaro commented on src/types/config.ts
> +		group?: boolean; // If true, group name to be the key
```suggestion
		group?: boolean; // If true, group name will be the token key
```

2020-02-17 20:19 UTC, thiagofuzaro commented on src/types/config.ts
> +		key?: string; // TODO: The key, sibling of the value on 'path' to be the token key; if group is true, this isn't necessary
```suggestion
		key?: string; // TODO: JSON file key who will be used to give this token a name. This key needs to be a sibling propperty of attribute 'path'
```

2020-02-17 20:19 UTC, thiagofuzaro commented on src/types/config.ts
> +		outputColorFormat?: Config["outputColorFormat"]; // Token specific format color
```suggestion
		outputColorFormat?: Config["outputColorFormat"]; // Token specific color format
```

2020-02-17 20:19 UTC, thiagofuzaro commented on src/types/config.ts
> +		prefix?: string; // String to concatenate before the value of tokens
```suggestion
		prefix?: string; // String to concatenate before token's values
```

2020-02-17 20:19 UTC, thiagofuzaro commented on src/types/config.ts
> +		suffix?: string; // String to concatenate after the value of tokens
```suggestion
		suffix?: string; // String to concatenate after token's value
```

2020-02-17 20:19 UTC, thiagofuzaro commented on src/types/config.ts
> +		styleKey?: "fill" | "text" | "effect" | "grid"; // Select the key from style object to find the style key
```suggestion
		styleKey?: "fill" | "text" | "effect" | "grid"; // Select key from style object to find the style key
```

2020-02-17 20:19 UTC, thiagofuzaro commented on src/types/config.ts
> +		type?: "group" | "rectangle" | "text"; // Specific the type object to find the token
```suggestion
		type?: "group" | "rectangle" | "text"; // Specify the object type to find the token
```

2020-02-17 20:19 UTC, thiagofuzaro commented on src/types/config.ts
> +		style?: boolean; // Use style id to generate the token; with this: 1 the `path` options is ignored; 2. and the `styleKey` is necessary;
```suggestion
		style?: boolean; // Used to named the token;
```

2020-02-17 20:19 UTC, thiagofuzaro commented on src/types/config.ts
> +		processValue?: "color" | "font" | "grid" | "radius" | "shadow"; // Help functions to auxiliate in process the token value
```suggestion
		processValue?: "color" | "font" | "grid" | "radius" | "shadow"; // Help functions to process the token value
```

2020-02-27 18:50 UTC, andredovale commented on src/types/config.ts
> +	apiBaseUrl: string; // Base URL from Figma API
4d54f77

2020-02-27 18:50 UTC, andredovale commented on src/types/config.ts
> +	figmaUrl: string; // URL from the project you need to extract the tokens
4d54f77

2020-02-27 18:50 UTC, andredovale commented on src/types/config.ts
> +	figmaToken: string; // Your user token from Figma to connect on Figma API
4d54f77

2020-02-27 18:51 UTC, andredovale commented on src/types/config.ts
> +	figmaPage: string; // Page from project to extract the tokens
4d54f77

2020-02-27 18:51 UTC, andredovale commented on src/types/config.ts
> +	outputColorFormat: "hexadecimal" | "hsl" | "hsla" | "rgb" | "rgba"; // TODO: Prefered format color to output the tokens (work with `token[#].processValue = "color";`)
4d54f77

2020-02-27 18:51 UTC, andredovale commented on src/types/config.ts
> +		suffix?: string; // String to concatenate after the value of tokens
4d54f77

2020-02-27 19:08 UTC, andredovale commented on src/types/config.ts
> +		styleKey?: "fill" | "text" | "effect" | "grid"; // Select the key from style object to find the style key
4d54f77

2020-02-27 19:08 UTC, andredovale commented on src/types/config.ts
> +		type?: "group" | "rectangle" | "text"; // Specific the type object to find the token
4d54f77

2020-02-27 19:09 UTC, andredovale commented on src/types/config.ts
> +		style?: boolean; // Use style id to generate the token; with this: 1 the `path` options is ignored; 2. and the `styleKey` is necessary;
4d54f77

2020-02-27 19:09 UTC, andredovale commented on src/types/config.ts
> +		processValue?: "color" | "font" | "grid" | "radius" | "shadow"; // Help functions to auxiliate in process the token value
4d54f77

2020-02-27 19:10 UTC, andredovale commented on src/types/config.ts
> +		| "vw"; // TODO: Prefered css unit to output the tokens
dc65c95

2020-02-27 19:10 UTC, andredovale commented on src/types/config.ts
> +	outputFigmaJsonPath: string; // Folder path for the original JSON from Figma API
dc65c95

2020-02-27 19:10 UTC, andredovale commented on src/types/config.ts
> +	outputFigmaJsonName: string; // File name for the original JSON from Figma API
dc65c95

2020-02-27 19:10 UTC, andredovale commented on src/types/config.ts
> +	outputFigmaTokensPath: string; // Folder path for the generated tokens
dc65c95

2020-02-27 19:10 UTC, andredovale commented on src/types/config.ts
> +	outputNameFormat: "camel" | "kebab" | "lower" | "snake" | "start" | "upper"; // Prefered string case to output the tokens keys
dc65c95

2020-02-27 19:10 UTC, andredovale commented on src/types/config.ts
> +		frameName: string | string[]; // Frame identification name on Figma Page (needed as direct child from page)
dc65c95

2020-02-27 19:10 UTC, andredovale commented on src/types/config.ts
> +		name: string; // Name of the file to output this token
dc65c95

2020-02-27 19:11 UTC, andredovale commented on src/types/config.ts
> +		path: string; // Path of the value for this token, in the same format from `lodash.get`
dc65c95

2020-02-27 19:11 UTC, andredovale commented on src/types/config.ts
> +		fallback?: string; // Used for cases when the path don't exist, but need to return a value to token
dc65c95

2020-02-27 19:11 UTC, andredovale commented on src/types/config.ts
> +		group?: boolean; // If true, group name to be the key
dc65c95

2020-02-27 19:11 UTC, andredovale commented on src/types/config.ts
> +		key?: string; // TODO: The key, sibling of the value on 'path' to be the token key; if group is true, this isn't necessary
dc65c95

2020-02-27 19:11 UTC, andredovale commented on src/types/config.ts
> +		outputColorFormat?: Config["outputColorFormat"]; // Token specific format color
dc65c95

2020-02-27 19:11 UTC, andredovale commented on src/types/config.ts
> +		prefix?: string; // String to concatenate before the value of tokens
dc65c95

2020-03-02 16:53 UTC, merged